config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :social_settings, only: [:edit, :update]
  end
end

app/controllers/spree/admin/social_settings_controller.rb
module Spree
  module Admin
    class SocialSettingsController < ResourceController
      def update
        settings = Spree::SocialSetting.new
        preferences = params && params.key?(:preferences) ? params.delete(:preferences) : params
        preferences.each do |name, value|
          next unless settings.has_preference? name.to_param
          settings[name] = value
        end
        flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:settings, scope: :social))
        redirect_to edit_admin_social_settings_path
      end
    end
  end
end

app/helpers/spree/base_helper_decorator.rb
module Spree
 module BaseHelperDecorator 

    def self.prepended(base)

    end
  
    def pin_it_button(product)
      return if product.images.empty?

      url = escape spree.product_url(product)
      media = absolute_product_image(product.images.first)
      description = escape product.name

      link_to('Pin It',
              "http://pinterest.com/pin/create/button/?url=#{url}&media=#{media}&description=#{description}",
              class: 'pin-it-button',
              'count-layout' => 'none').html_safe
    end

    def absolute_product_image(image)
      escape absolute_image_url(image.attachment.url)
    end

    def absolute_image_url(url)
      return url if url.starts_with? 'http'
      request.protocol + request.host + url
    end

    private

    def escape(string)
      URI.escape string, /[^#{URI::PATTERN::UNRESERVED}]/
    end
  end
end
# ::Spree::BaseHelper.prepend(Spree::BaseHelperDecorator)

::Spree::BaseHelper.prepend Spree::BaseHelperDecorator if ::Spree::BaseHelper.included_modules.exclude?(Spree::BaseHelperDecorator)

app/views/spree/admin/social_settings/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:settings, scope: :social) %>
<% end %>

<%= form_tag admin_social_settings_path, method: :put do %>
  <fieldset>
    <div data-hook="admin_social_method_form_fields">
      <div class="row">
        <div class="col-md-6" data-hook="social">

          <fieldset>
            <legend><%= Spree.t(:service_settings, scope: :social) %></legend>
            <div class="form-group">
              <% Spree::Social::Config.social_services.each do |service| -%>
                <% name = "#{service}_button".to_sym %>
                <div class="checkbox">
                  <%= label_tag name do %>
                    <%= preference_field_tag name, Spree::Social::Config[name], type: :boolean %>
                    <%= Spree.t(:service_button, scope: [:social, :preferences], service: service.to_s.titleize) %>
                  <% end %>
                </div>
              <%- end %>
            </div>
          </fieldset>

        </div>

        <div class="col-md-6" data-hook="facebook">

          <fieldset>
            <legend><%= Spree.t(:facebook_settings, scope: :social) %></legend>

            <div id="facebook_options">
              <div class="form-group">
                <div class="checkbox">
                  <%= label_tag :facebook_show_faces do %>
                    <%= preference_field_tag :facebook_show_faces, Spree::Social::Config[:facebook_show_faces], type: :boolean %>
                    <%= Spree.t :facebook_show_faces, scope: [:social, :preferences] %>
                  <% end %>
                </div>

                <div class="checkbox">
                  <%= label_tag :facebook_send_button do %>
                    <%= preference_field_tag :facebook_send_button, Spree::Social::Config[:facebook_send_button], type: :boolean %>
                    <%= Spree.t :facebook_send_button, scope: [:social, :preferences] %>
                  <% end %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :facebook_app_id, Spree.t(:facebook_app_id, scope: [:social, :preferences]) %>
                <%= password_field_tag :facebook_app_id, Spree::Social::Config[:facebook_app_id], class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= label_tag :facebook_layout, Spree.t(:facebook_layout, scope: [:social, :preferences]) %>
                <%= select_tag :facebook_layout, options_for_select(Spree::Social::Config.facebook_layouts, Spree::Social::Config[:facebook_layout]), class: 'select2' %>
              </div>

              <div class="form-group">
                <%= label_tag :facebook_verb_to_display, Spree.t(:facebook_verb_to_display, scope: [:social, :preferences]) %>
                <%= select_tag :facebook_verb_to_display, options_for_select(Spree::Social::Config.facebook_verbs, Spree::Social::Config[:facebook_verb_to_display]), class: 'select2' %>
              </div>

              <div class="form-group">
                <%= label_tag :facebook_color_scheme, Spree.t(:facebook_color_scheme, scope: [:social, :preferences]) %>
                <%= select_tag :facebook_color_scheme, options_for_select(Spree::Social::Config.facebook_color_schemes, Spree::Social::Config[:facebook_color_scheme]), class: 'select2' %>
              </div>
            </div>

          </fieldset>
        </div>

        <div class="col-md-6" data-hook="twitter">
          <fieldset>
            <legend><%= Spree.t(:twitter_settings, scope: :social) %></legend>

            <div id="twitter_options">
              <div class="form-group">
                <%= label_tag :twitter_id, Spree.t(:twitter_id, scope: [:social, :preferences]) %>
                <%= text_field_tag :twitter_id, Spree::Social::Config[:twitter_id], class: 'form-control' %>
              </div>
            </div>
          </fieldset>
        </div>
      </div>

      <div class="form-actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'save' %>
      </div>

    </div>
  </fieldset>
<% end %>

app/views/spree/shared/_fb_script.html.erb
<script type="text/javascript">
  var bindFacebookEvents, fb_events_bound, fb_root, initializeFacebookSDK, loadFacebookSDK, restoreFacebookRoot, saveFacebookRoot;

  fb_root = null;

  fb_events_bound = false;

  $(function() {
    loadFacebookSDK();
    if (!fb_events_bound) {
      return bindFacebookEvents();
    }
  });

  bindFacebookEvents = function() {
    $(document).on('page:fetch', saveFacebookRoot).on('page:change', restoreFacebookRoot).on('page:load', function() {
      return typeof FB !== "undefined" && FB !== null ? FB.XFBML.parse() : void 0;
    });
    return fb_events_bound = true;
  };

  saveFacebookRoot = function() {
    return fb_root = $('#fb-root').detach();
  };

  restoreFacebookRoot = function() {
    if ($('#fb-root').length > 0) {
      return $('#fb-root').replaceWith(fb_root);
    } else {
      return $('body').append(fb_root);
    }
  };

  loadFacebookSDK = function() {
    window.fbAsyncInit = initializeFacebookSDK;
    return $.getScript("//connect.facebook.net/en_US/all.js#xfbml=1");
  };

  initializeFacebookSDK = function() {
    return FB.init({
      appId: "<%= Spree::Social::Config.preferred_facebook_app_id %>",
      status: true,
      cookie: true,
      xfbml: true
    });
  };
</script>

app/views/spree/shared/_social_buttons.html.erb
<div id="social_nav">
  <h6><%= Spree.t(:bookmark_or_share_this, scope: :social) %></h6>
  <ul>
    <% if Spree::Social::Config.preferred_twitter_button %>
      <li class="twitter">
        <%= render 'spree/social/twitter' %>
      </li>
    <% end %>
    <% if Spree::Social::Config.preferred_pinterest_button %>
      <li class="pinterest">
        <%= render 'spree/social/pinterest' %>
      </li>
    <% end %>
    <% if Spree::Social::Config.preferred_reddit_button %>
      <li class="reddit">
        <%= render 'spree/social/reddit' %>
      </li>
    <% end %>
    <% if Spree::Social::Config.preferred_tumblr_button %>
      <li class="tumblr">
        <%= render 'spree/social/tumblr' %>
      </li>
    <% end %>
    <% if Spree::Social::Config.preferred_delicious_button %>
      <li class="delicious">
        <%= render 'spree/social/delicious' %>
      </li>
    <% end %>
    <% if Spree::Social::Config.preferred_google_plus_button %>
      <li class="google_plus">
        <%= render 'spree/social/google_plus' %>
      </li>
    <% end %>
  </ul>
  <ul class="facebook-like-button">
    <% if Spree::Social::Config.preferred_facebook_button %>
      <li class="facebook">
        <%= render 'spree/social/facebook' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/spree/social/_delicious.html.erb
<a href="http://www.delicious.com/save" onclick="window.open('http://www.delicious.com/save?v=5&noui&jump=close&url='+encodeURIComponent(location.href)+'&amp;title='+encodeURIComponent(document.title),'delicious','toolbar=no,width=550,height=550'); return false;">
  <img src="/assets/social/delicious.png" height="19" width="19" alt="<%= Spree.t(:delicious, scope: [:social, :buttons]) %>" />
</a>

app/views/spree/social/_facebook.html.erb
<% unless Spree::Social::Config.preferred_facebook_app_id.nil? %>
  <% content_for :head do %>
    <meta property="og:title" content="<%= @product.name %>" />
    <meta property="og:type" content="product" />
    <meta property="og:url" content="<%= spree.product_url(@product) %>" />
    <meta property="og:description" content="<%= @product.description %>" />
    <% @product.images.each do |img| %>
      <meta property="og:image" content="<%= url_for(img) rescue ''%>" />
    <% end %>
    <meta property="fb:app_id" content="<%= Spree::Social::Config.preferred_facebook_app_id %>" />
  <% end %>

  <div id="fb-root"></div>

  <div
    class="fb-like"
    data-send="<%= Spree::Social::Config.preferred_facebook_send_button %>"
    data-width="450"
    data-show-faces="<%= Spree::Social::Config.preferred_facebook_show_faces %>"
    data-layout="<%= Spree::Social::Config.preferred_facebook_layout %>"
    data-colorscheme="<%= Spree::Social::Config.preferred_facebook_color_scheme %>"
    data-action="<%= Spree::Social::Config.preferred_facebook_verb_to_display %>"></div>
<% end %>

app/views/spree/social/_google_plus.html.erb
<g:plusone size="medium"></g:plusone>

<!-- Place this render call where appropriate -->
<script>
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

app/views/spree/social/_pinterest.html.erb
<%= pin_it_button(@product) %>
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>

app/views/spree/social/_reddit.html.erb
<a href="http://www.reddit.com/submit" onclick="window.location = 'http://www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false">
  <img src="http://www.reddit.com/static/spreddit1.gif" alt="<%= Spree.t(:submit_to_reddit, scope: [:social, :buttons]) %>" border="0" /> 
</a>

app/views/spree/social/_tumblr.html.erb
<% title = Spree.t(:share_on_tumblr, scope: [:social, :buttons]) %>
<%= link_to 'http://www.tumblr.com/share/link?' + { url: spree.product_url(@product), name: @product.name, description: @product.description }.to_param, title: title, class: 'tumblr-share' do %>
  <%= title %>
<% end %>

<script src="//platform.tumblr.com/v1/share.js"></script>

app/views/spree/social/_twitter.html.erb
<% content_for :head do %>
  <meta property="twitter:card" content="product" />
  <% unless Spree::Social::Config.preferred_twitter_id.nil? %>
    <meta property="twitter:site" content="<%= Spree::Social::Config.preferred_twitter_id %>" />
  <% end %>
  <meta property="twitter:title" content="<%= @product.name %>" />
  <meta property="twitter:description" content="<%= @product.description %>" />
  <meta property="twitter:image" content="<%= small_image(@product) %>" />
  <% unless @product.price.nil? %>
    <meta property="twitter:label1" content="<%= Spree.t(:price) %>" />
    <meta property="twitter:data1" content="<%= @product.price_in(current_currency).money %>" />
  <% end %>
<% end %>

<a href="https://twitter.com/share" class="twitter-share-button" data-count="none">
  <%= Spree.t(:tweet, scope: [:social, :buttons]) %>
</a>
<script src="//platform.twitter.com/widgets.js"></script>